/**
 * Extra fictional weavers for nationwide buyer map clusters (Demo Mode).
 * Stable ids — stock/rating derived deterministically; not in Postgres identity.
 */

export type MapDemoWeaver = {
  id: string;
  name: string;
  region: string;
  district: string;
  categories: string[];
  cooperativeName: string;
};

export const NATIONAL_MAP_DEMO_WEAVERS: MapDemoWeaver[] = [
  // Delhi primary cluster (IIT → district → nation)
  {
    id: "map-weaver-iit-01",
    name: "Meera",
    region: "Delhi",
    district: "IIT Delhi",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-iit-02",
    name: "Ritu",
    region: "Delhi",
    district: "IIT Delhi",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-hauz-01",
    name: "Nisha",
    region: "Delhi",
    district: "Hauz Khas",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-south-01",
    name: "Kavya",
    region: "Delhi",
    district: "South Delhi",
    categories: ["silk saree", "dhoti / angavastram"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-saket-01",
    name: "Anjali",
    region: "Delhi",
    district: "Saket",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-newdelhi-01",
    name: "Priya",
    region: "Delhi",
    district: "New Delhi",
    categories: ["cotton saree"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-karol-01",
    name: "Sonal",
    region: "Delhi",
    district: "Karol Bagh",
    categories: ["stole / dupatta", "cotton saree"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-chandni-01",
    name: "Farida",
    region: "Delhi",
    district: "Chandni Chowk",
    categories: ["stole / dupatta", "cotton lungi"],
    cooperativeName: "Yamuna Loom Desk",
  },
  {
    id: "map-weaver-kanchi-01",
    name: "Revathi",
    region: "Tamil Nadu",
    district: "Kanchipuram",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-kanchi-02",
    name: "Padma",
    region: "Tamil Nadu",
    district: "Kanchipuram",
    categories: ["silk saree"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-salem-01",
    name: "Kavitha",
    region: "Tamil Nadu",
    district: "Salem",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-erode-01",
    name: "Anitha",
    region: "Tamil Nadu",
    district: "Erode",
    categories: ["cotton saree", "cotton lungi"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-madurai-01",
    name: "Thenmozhi",
    region: "Tamil Nadu",
    district: "Madurai",
    categories: ["silk saree", "dhoti / angavastram"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-varanasi-01",
    name: "Sunita",
    region: "Uttar Pradesh",
    district: "Varanasi",
    categories: ["silk saree"],
    cooperativeName: "Ganga Plains Handloom",
  },
  {
    id: "map-weaver-varanasi-02",
    name: "Asha",
    region: "Uttar Pradesh",
    district: "Varanasi",
    categories: ["silk saree", "stole / dupatta"],
    cooperativeName: "Ganga Plains Handloom",
  },
  {
    id: "map-weaver-mau-01",
    name: "Geeta",
    region: "Uttar Pradesh",
    district: "Mau",
    categories: ["cotton saree", "silk saree"],
    cooperativeName: "Ganga Plains Handloom",
  },
  {
    id: "map-weaver-pochampally-01",
    name: "Lakshmi Bai",
    region: "Telangana",
    district: "Pochampally",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Deccan Handloom Desk",
  },
  {
    id: "map-weaver-gadwal-01",
    name: "Saraswati",
    region: "Telangana",
    district: "Gadwal",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Deccan Handloom Desk",
  },
  {
    id: "map-weaver-ilkal-01",
    name: "Bhagirathi",
    region: "Karnataka",
    district: "Ilkal",
    categories: ["cotton saree", "silk saree"],
    cooperativeName: "Mysore Loom Collective",
  },
  {
    id: "map-weaver-mysuru-01",
    name: "Nirmala",
    region: "Karnataka",
    district: "Mysuru",
    categories: ["silk saree"],
    cooperativeName: "Mysore Loom Collective",
  },
  {
    id: "map-weaver-sualkuchi-01",
    name: "Bina",
    region: "Assam",
    district: "Sualkuchi",
    categories: ["silk saree", "stole / dupatta"],
    cooperativeName: "Brahmaputra Loom Circle",
  },
  {
    id: "map-weaver-shantipur-01",
    name: "Rina",
    region: "West Bengal",
    district: "Shantipur",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Ganga Weave Collective",
  },
  {
    id: "map-weaver-phulia-01",
    name: "Mala",
    region: "West Bengal",
    district: "Phulia",
    categories: ["cotton saree"],
    cooperativeName: "Ganga Weave Collective",
  },
  {
    id: "map-weaver-sambalpur-01",
    name: "Priya",
    region: "Odisha",
    district: "Sambalpur",
    categories: ["cotton saree", "stole / dupatta"],
    cooperativeName: "Kalinga Loom Circle",
  },
  {
    id: "map-weaver-nuapatna-01",
    name: "Smita",
    region: "Odisha",
    district: "Nuapatna",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Kalinga Loom Circle",
  },
  {
    id: "map-weaver-mangalagiri-01",
    name: "Vani",
    region: "Andhra Pradesh",
    district: "Mangalagiri",
    categories: ["cotton saree", "cotton lungi"],
    cooperativeName: "Godavari Thread Circle",
  },
  {
    id: "map-weaver-dharmavaram-01",
    name: "Jyothi",
    region: "Andhra Pradesh",
    district: "Dharmavaram",
    categories: ["silk saree"],
    cooperativeName: "Godavari Thread Circle",
  },
  {
    id: "map-weaver-chanderi-01",
    name: "Radha",
    region: "Madhya Pradesh",
    district: "Chanderi",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Kalinga Loom Circle",
  },
  {
    id: "map-weaver-paithan-01",
    name: "Savita",
    region: "Maharashtra",
    district: "Paithan",
    categories: ["silk saree"],
    cooperativeName: "Mysore Loom Collective",
  },
  {
    id: "map-weaver-patan-01",
    name: "Hetal",
    region: "Gujarat",
    district: "Patan",
    categories: ["silk saree", "stole / dupatta"],
    cooperativeName: "Mysore Loom Collective",
  },
  {
    id: "map-weaver-kannur-01",
    name: "Latha",
    region: "Kerala",
    district: "Kannur",
    categories: ["cotton saree", "dhoti / angavastram"],
    cooperativeName: "Nila Loom Circle",
  },
  {
    id: "map-weaver-bhagalpur-01",
    name: "Poonam",
    region: "Bihar",
    district: "Bhagalpur",
    categories: ["silk saree", "cotton saree"],
    cooperativeName: "Ganga Plains Handloom",
  },
];

/** Stable district for seeded Postgres demo weavers. */
export const DEMO_WEAVER_DISTRICTS: Record<
  string,
  { region: string; district: string }
> = {
  "weaver-demo-001": { region: "Delhi", district: "IIT Delhi" },
  "weaver-demo-002": { region: "Delhi", district: "South Delhi" },
  "weaver-demo-003": { region: "Delhi", district: "Hauz Khas" },
  "weaver-demo-004": { region: "Delhi", district: "Saket" },
};
